FROM node:18.18.2

ARG web=/opt/workspace/dapp
ARG NEXT_PUBLIC_APP_ENV
ARG NODE_ENV
ARG BUILD_ENV
ENV NEXT_PUBLIC_APP_ENV=${NEXT_PUBLIC_APP_ENV}
ENV NODE_ENV=${NODE_ENV}

WORKDIR ${web}

COPY . ${web}

RUN yarn && yarn build:${BUILD_ENV}

ENTRYPOINT yarn start

EXPOSE 3000
