/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        brandDefault: 'var(--brand-default)',
        brandHover: 'var(--brand-hover)',
        brandClick: 'var(--brand-click)',
        brandDisable: 'var(--brand-disable)',
        brandBg: 'var(--brand-bg)',
        neutralTitle: 'var(--neutral-title)',
        neutralPrimary: 'var(--neutral-primary)',
        neutralSecondary: 'var(--neutral-secondary)',
        neutralTertiary: 'var(--neutral-tertiary)',
        neutralDisable: 'var(--neutral-disable)',
        neutralBorder: 'var(--neutral-border)',
        neutralDivider: 'var(--neutral-divider)',
        neutralDefaultBg: 'var(--neutral-default-bg)',
        neutralHoverBg: 'var(--neutral-hover-bg)',
        neutralWhiteBg: 'var(--neutral-white-bg)',
        functionalSuccess: 'var(--functional-success)',
        functionalWarning: 'var(--functional-warning)',
        functionalLinkBg: 'var(--functional-link-bg)',
        functionalSuccessBg: 'var(--functional-success-bg)',
        functionalWarningBg: 'var(--functional-warning-bg)',
        functionalDanger: 'var(--functional-danger)',
        functionalDangerBg: 'var(--functional-danger-bg)',
        functionalDangerHover: 'var(--functional-danger-hover)',
        functionalDangerClick: 'var(--functional-danger-click)',
        functionalDangerDisable: 'var(--functional-danger-disable)',
        fillMask1: 'var(--fill-mask-1)',
      },
      fontSize: {
        xs: ['12px', '20px'],
        sm: ['14px', '22px'],
        base: ['16px', '24px'],
        lg: ['18px', '26px'],
        xl: ['20px', '28px'],
        '2xl': ['24px', '32px'],
        '3xl': ['28px', '36px'],
        '4xl': ['32px', '40px'],
        '5xl': ['40px', '48px'],
        '6xl': ['48px', '56px'],
      },
      keyframes: {
        loading: {
          '0%': { transform: 'rotate(0)' },
          '50%': { transform: 'rotate(-180deg)' },
          '100%': { transform: 'rotate(-360deg)' },
        },
      },
      animation: {
        loading: 'loading 800ms linear infinite',
      },
      borderRadius: {
        sm: '6px',
        md: '8px',
        lg: '12px',
      },
    },
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
      large: '2560px',
      main: '1440px',
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
